name: preditickertest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==1.4.3
  - fbprophet==0.7.1
  - Pillow==9.2.0
  - Pystan==2.19.1.1
  - pip
  - pip:
    - plotly==5.9.0
    - requests==2.28.1
    - streamlit==1.11.0
    - streamlit_option_menu==0.3.2
    - mplfinance==0.12.9b1
    - yfinance==0.1.74
    - tweepy==4.10.0
