name: preditickertest
channels:
  - conda-forge
  - defaults
dependencies:
  - plotly==5.9.0
  - pandas==1.4.3
  - numpy==1.23.1
  - fbprophet==0.7.1
  - requests==2.28.1
  - Pillow==9.2.0
  - pip
  - pip:
    - Pystan==2.19.1.1
    - streamlit==1.11.0
    - yfinance==0.1.74
    - tweepy==4.10.0
